# Generated by Django 3.2 on 2023-05-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('unique_cookie', models.BigIntegerField()),
                ('password', models.TextField()),
            ],
        ),
    ]
