# Generated by Django 3.2 on 2023-05-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authconstrux', '0002_usersinfo_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinfo',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
    ]
