# Generated by Django 3.2 on 2023-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authconstrux', '0005_auto_20230524_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinfo',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
