# Generated by Django 3.2 on 2023-05-22 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('authconstrux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfo',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.cart'),
        ),
    ]
