# Generated by Django 3.2 on 2023-05-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('authconstrux', '0004_alter_usersinfo_unique_cookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinfo',
            name='cart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.cart'),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='unique_cookie',
            field=models.BigIntegerField(blank=True),
        ),
    ]
